### PR TITLE
Added applicants serializer

### PR DESCRIPTION
**Pull request by allthesignals**
Includes dynamic attributes in the serializer.

### CODE REVIEW

**Comment by mzagaja** [comment]
Did you forget to check-in a migration and/or applicants_helper.rb?

**Comment by allthesignals** [comment]
@mzagaja There's nothing in the applicants helper so I removed it - happy to add it back if you think it's needed. The schema change I will be reverting - that's from the one-off CBO form deployment, which I don't want to merge into this.

**Comment by mzagaja** [comment]
Ok, in that case I'd just also remove the associated test file in spec. Otherwise this looks great.

**Comment by allthesignals** [comment]
Removed the applicants helper spec and schema change.

**Pull request merged**
